# Generated by Django 5.0.4 on 2024-04-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('first_level', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('second_level', models.TextField(max_length=30)),
                ('level_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_level', to='just_menu.levelone')),
            ],
        ),
        migrations.CreateModel(
            name='LevelThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('third_level', models.TextField(max_length=30)),
                ('level_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_level', to='just_menu.leveltwo')),
            ],
        ),
    ]
