# Generated by Django 5.0.4 on 2024-04-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelone',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='levelthree',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='leveltwo',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='levelone',
            name='first_level',
            field=models.TextField(max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='levelthree',
            name='third_level',
            field=models.TextField(max_length=30, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='leveltwo',
            name='second_level',
            field=models.TextField(max_length=30, verbose_name='Производитель'),
        ),
    ]
