# Generated by Django 5.0.4 on 2024-04-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('just_menu', '0003_remove_levelone_number_remove_levelthree_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LevelOne',
            new_name='First',
        ),
        migrations.RenameModel(
            old_name='LevelTwo',
            new_name='Second',
        ),
        migrations.RenameModel(
            old_name='LevelThree',
            new_name='Third',
        ),
    ]
